export const UPDATE_FEELING = 'UPDATE_FEELING';
export const UPDATE_UNDERSTANDING = 'UPDATE_UNDERSTANDING';
export const UPDATE_SUPPORT = 'UPDATE_SUPPORT';
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS';
export const RESET_FORM = 'RESET_FORM';